server:
  address: 127.0.0.1
  port: 8080

### Prod DB
spring:
  datasource:
    url: jdbc:mysql://event-centre.coaxeduspmjg.us-west-1.rds.amazonaws.com/event_centre
    username: admin
    password: admin275

  jpa:
    hibernate:
      ddl-auto: update
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: cloudeventc@gmail.com
    password: Sjsu@123456
    properties:
      mail:
       smtp:
        auth: true
        starttls:
          enable: true
#  security:
#      oauth2:
#        client:
#          registration:
#            google:
#              clientId: 162062109197-p1uigbcd3tk65fvopdb9ojjud2r75uiu.apps.googleusercontent.com
#              clientSecret: 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
#              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#              scope:
#                - email
#                - profile