server:
  address: 127.0.0.1
  port: 8080

### Prod DB
spring:
  datasource:
    url: jdbc:mysql://db-275.csrl9wbmcemv.us-west-1.rds.amazonaws.com/event_centre
    username: admin
    password: admin275

  jpa:
    hibernate:
      ddl-auto: update